### ISSUE TITLE
Remove package version from constants

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-Flutter#809]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

### Current Limitation

The package version is currently defined as a constant in addition to the definition in the pubspec file:

```
 const String keySdkVersion = '3.1.5';
 const String keyLibraryName = 'Flutter Parse SDK';
```

This means that for a release, the version constant above and the version in the pubspec file need to be changed. This creates a risk that one of the two is not updated by mistake which creates an inconsistency.

### Feature / Enhancement Description

Find a way to define the package version number in only 1 place.

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

**Comment by mbfakourii** [comment]
This variable is only  sent to the server as the version of the request in a header, in the ```parseVersion``` and ```user-agent``` keys.

Why should the version be sent to the server? @mtrezza What is the need?

**Comment by mbfakourii** [comment]
This variable is sent to the server as the version of the request in a header, in the ```parseVersion``` and ```user-agent``` keys

Is it possible to change with ci?

**Comment by mtrezza** [comment]
The version numbers will be bumped automatically once we added release automation to this repo.
Until then we could add a CI step that at least fails if the version is out of sync with the pubspec version.
But in any case, doesn't the package know its own version?

**Comment by mbfakourii** [comment]
The package only knows its version from the pubspec file.

**Comment by mtrezza** [comment]
The what do we need the `keySdkVersion` variable for?

**Comment by mbfakourii** [comment]
> The what do we need the `keySdkVersion` variable for?

This variable is sent to the server as the version of the request in a header, in the ```parseVersion``` and ```user-agent``` keys
> Can't the SDK send the version defined in the pubspec file?

Unfortunately, it is not possible to access this value, the only way is the [```package_info_plus```](https://pub.dev/packages/package_info_plus) package, which does not support Dart

**Comment by mtrezza** [comment]
Alright, I'll cose this for now; once we have auto-release added, this isn't an issue anymore anyway.
