### ISSUE TITLE
Add Flutter and Dart versions when filling out an issue in the Environment section 

### ISSUE THREAD

**Issue by Nidal-Bakir** [parse-community/Parse-SDK-Flutter#862]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

### Current Limitation

Currently, when a developer reports an issue, we do not request information about the Flutter or Dart versions being used. Having this information would be helpful when trying to fix the issue, as it would allow us to know the exact environment in which the issue was reported

### Feature / Enhancement Description

Add Flutter and Dart versions when filling out an issue in the Environment section

### Example Use Case

See #861 if the developer did not provide the Flutter version in a new "Additional content" section we would not know whether they are using a stable, beta, or pre-release of Flutter

### Alternatives / Workarounds

N/A
