### ISSUE TITLE
Improve dart pub points scoring on pub.dev

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-Flutter#882]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Issue Description

pub.dev [pub points](https://pub.dev/packages/parse_server_sdk/score) analysis shows:

1. Maybe we need to remove the upper bound `<3.1.0` because pub.dev doesn't like clear compatibility specifications:

> Unable to run pub upgrade.
> The current Dart SDK version is 3.1.0-63.1.beta.
> 
> Because parse_server_sdk requires SDK version >=2.18.0 <3.1.0, version solving failed.
> 
> You can try the following suggestion to make the pubspec resolve:
> * Try using the Dart SDK version: 3.0.0. See https://dart.dev/get-dart.

Also interesting, it's using a beta version of dart 3.1 (there has been no stable 3.1 release yet) to determine compatibility. An odd choice to let a beta version determine the public scoring of a package.

2. The package description is too short:

> Add more detail to the description field of pubspec.yaml. Use 60 to 180 characters to describe the package, what it does, and its target use case.

3. No example:

> 0/10 points: Package has an example
>  No example found.

**Comment by mbfakourii** [comment]
@mtrezza 
Should I make a PR for the Flutter version as well? Or create another PR?
