### ISSUE TITLE
Incorrect Dart support policy

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-Flutter#968]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Issue Description

It seems we have an mistake in our support policy, which says:

> To give developers time to upgrade their app to the newest Dart framework, previous Dart framework releases are supported for at least 1 year after their [release date](https://dart.dev/get-dart/archive).

The end-of-support date needs to depend on how long a newer significant (=minor) release is available to give developers time to upgrade. Dart 3 has been released in [May 2023](https://dart.dev/guides/whats-new#may-10-2023-30-release). So we'd support Dart 2.19 until May 2024. That gives developers 12 months to upgrade.

**Comment by mbfakourii** [comment]
In my opinion, one year is too much time. If the developers are not interested in updating and using the new version, they can still use the old version of the package.

In my opinion, this policy also annoys the developers, it makes us unable to use new features for up to 1 year! And this actually slows down the development of the package.

**Comment by mtrezza** [comment]
> it makes us unable to use new features for up to 1 year

Can you give an example?

**Comment by mtrezza** [comment]
> One of the new features of Dart 3 is [Multiple returns](https://dart.dev/language/records#multiple-returns), which allows us to have multiple output values in the function

The question is whether that prohibits Parse SDK development, or it's just less convenient because it doesn't allow us to use the latest greatest Dart features when developing the SDK. For a developer who is using the Parse SDK this should be irrelevant as long as it's not affecting their own development.

>  I think they offer a new version almost every two weeks.

We only care for breaking releases (minor releases in the Dart world), which currently seem to happen about every 4-5 months.

**Comment by mbfakourii** [comment]
> The question is whether that impedes Parse SDK development, or it's just less convenient because it doesn't allow us to use the latest greatest Dart features when developing the SDK. For a developer who is using the Parse SDK this should be irrelevant as long as it's not affecting their own development. For Parse SDK maintainers that should be acceptable as long as it doesn't significantly increase maintenance effort.

In addition, it impedes development, it also prevents developers from using other packages that do not support versions below 3 !

For example, a package that does not support the version below Dart 3 cannot be in the same project as our package!

> We only care for breaking releases (minor releases in the Dart world), which currently seem to happen about every 4-5 months. We could think about reducing the support time from 12 to 6 months, if we can find real examples that show a significant increase in maintenance effort because of the 12 months support. Also, if you could find Dart adoption statistics of apps somewhere, and we see for example that in the Dart world, 80% of developers upgrade their app to the latest significant Dart release within n months, we can adapt our support policy.

It is better to ask the question in the [Dart repository](https://github.com/dart-lang/sdk/issues).


Another thing is that all the packages that are currently available in [Flutter packages](https://github.com/flutter/flutter/tree/master/packages), none of them support below 3! [[1](https://github.com/flutter/flutter/blob/bea63d7c81760b6bff5fabfb954834a037180d60/packages/flutter_test/pubspec.yaml#L4)]

**Comment by mtrezza** [comment]
> it also prevents developers from using other packages that do not support versions below 3 !

Why? If someone wants to use Dart 3, they can do it as the Parse SDK supports it.

**Comment by mbfakourii** [comment]
> Are you talking about app developers, and if yes, why would that be? If someone wants to use Dart 3, they can do it as the Parse SDK supports it.

I think I explained it wrong. For example, when a developer uses version `2.8` of Dart, in order to use a package that supports version `3` and above, he must update himself, which is not a problem on the developers' side.

But when we want to use a package in our package that supports version ```3``` and above, we encounter a problem in CI because it is not possible to use it in version ```2.8``` or ```2.9```.

If we skip from our CI and CI no longer checks the old versions below 3. When the developer adds our new version, he encounters a message that he should upgrade to the new version of Dart.

If the developer has secrets about using the old version of Dart, he can use the old version of our package!

And currently, most of the famous packages no longer support versions below ```3```. If you check the [pub.dev](https://pub.dev/) site, you will understand this!

**Comment by mtrezza** [comment]
> And currently, most of the famous packages no longer support versions below 3. If you check the [pub.dev](https://pub.dev/) site, you will understand this!

Let's do a quick analysis.

There are two different aspects: "compatibility with Dart 3" vs. "required min Dart SKD version 3". 

Looking at the packages listed on the overview page you linked we can see these min Dart SDK versions:

| Group | Min Dart SDK |
| --- | --- |
| Flutter Favorites |  2.12, 2.17,  2.14, 2.12 |
| Most popular packages | 2.18, 3.0, 3.0, 2.12, 2.18, 2.12 |
| Top Flutter packages |  2.18, 2.15, 2.12, 2.16, 2.17, 2.19 |
| Top Dart packages |  2.12, 2.12, 2.19, 2.12, 2.12, 2.12 |

- All of these packages are "Dart 3 compatible".
- Only 3 packages require a min Dart SDK version of 3, that's only 9%.

Let's take a look at the min SDK distribution:

| Min Dart SDK | Count |
| --- | --- |
| 3.0 | 2 |
| 2.19 | 2 |
| 2.18| 3 |
| 2.17 | 2 |
| 2.16 | 1 |
| 2.15 | 1 |
| 2.14 | 1 |
| 2.12 | 10 |

- This is a bimodal distribution. The first peak (2.18) are the " moderate speed adopters" which take about a year (Dart 2.29 was released in Jan 2023) to upgrade. The second peak (2.12) is most likely a deliberate choice to support older Dart versions, because all of these packages are well maintained; it shows that 45% of the most popular Dart and Flutter packages still support Dart 2.12.

Looking at the `firebase_core` package as an example: the min SDK was raised to `2.18` in March 2023, but Dart 2.18 was released in August 2022. Developers had 9 month to upgrade their app, meanwhile they were able to upgrade the package with bug fixes and new features.

The fundamental problem with increasing the min Dart SDK version fast is that the time a package maintainer takes to make their package "Dart 3 compatible" varies. If an app has 10 packages and only 1 package requires a min Dart SDK version of 3, then all other 9 packages must be Dart 3 compatible in order to upgrade to Dart 3. Otherwise the developer must look for alternative packages that already support Dart 3 (higher development effort), or cannot upgrade to use the latest release of that one package that requires Dart 3.

The developer is between the front lines of package maintainers. The more rapidly we increase the min Dart SDK version, the more difficult we make life for developers who use the Parse Platform SDK. We need to strike a balance, and I would say from the data above that balance is somewhere between Dart 2.18 and 2.12.

**Comment by mbfakourii** [comment]
Great analysis, I'm convinced, but what do you suggest? Is the support period the same as one year?

**Comment by mtrezza** [comment]
In time terms:
- Dart 2.18, released Aug 2022 -> time passed since release: 1 year + 1 month
- Dart 2.12, released Mar 2021 -> time passed since release: 2 years + 6 months months

That means that the Parse SDK's support policy of 1 year is already on the lower end of the range. Unless there is a critical reason I would keep it at 1 year.

**Comment by mbfakourii** [comment]
> In time terms:
> 
> * Dart 2.18, released Aug 2022 -> time passed since release: 1 year + 1 month
> * Dart 2.12, released Mar 2021 -> time passed since release: 2 years + 6 months months
> 
> That means that the Parse SDK's support policy of 1 year is already on the lower end of the range. Unless there is a critical reason - which we would evaluate on a per-case basis - I would keep it at 1 year.
> 
> What we could do now is to open a PR that removes Dart 18 support (it's already >1 year old) and fix the wording in the support policy, which is the original issue opened.

Yes, it is a good suggestion

**Comment by mtrezza** [comment]
Would you want to do the honors? 🙂

**Comment by mbfakourii** [comment]
> Would you want to do the honors? 🙂

Sure 😃

**Comment by mtrezza** [comment]
Yes, from the CI you'd remove Dart 2.18. And we should add Dart 3.1 compatibility. We can do this in 1 PR, the PR will be a `feat` PR because of the added Dart 3.1 compatibility, with a breaking change because of the removal of Dart 2.18 compatibility.

**Comment by mbfakourii** [comment]
> Yes, from the CI you'd remove Dart 2.18. And we should add Dart 3.1 compatibility. You could do this in 1 PR. The PR would be a `feat` PR because of the added Dart 3.1 compatibility, with a breaking change label because of the removal of Dart 2.18 compatibility.

Yes, I will try to open the PR by the end of today

**Comment by chadpav** [comment]
Great discussion! 

It's interesting that I had a similar versioning issue with a different, but popular, package https://github.com/parse-community/Parse-SDK-Flutter/pull/1002 about 1 year later. All I'm saying is that there may be something to the Flutter community being new and evolving quickly that makes this discussion more interesting. 

This issue resulted in me forking the Flutter SDK and fixing it locally. Later, I ended up realizing that I didn't need the functionality in the Flutter SDK and that the Dart SDK didn't have that dependency. So I switched packages. I even took the time to update the Flutter SDK package and submit a PR but was blocked due to the backward compatibility policy. **It was the right call because we should respect the policies that we have in place.** But in the end, I was frustrated and felt like I wasted several days on it. 

Taking the other side I want to make a hypothetical argument. What would happen if we were to bump major versions of our SDK when backward compatibility breaks and keep up with the latest dependencies? If there were a critical bug on an older version of this SDK and a developer were stuck in maintenance mode they would be forced to patch an old release of the SDK or figure out a path forward through breaking changes?

We've seen at least two examples of the former. Would it be less pain to deal with the latter on an exceptional basis?

**Comment by mtrezza** [comment]
> What would happen if we were to bump major versions of our SDK when backward compatibility breaks and keep up with the latest dependencies?

How would such a policy be clearly defined in practice, so that there are no discussions required in order to follow the policy? This is one important criteria, for efficiency and predictability.


> If there were a critical bug on an older version of this SDK and a developer were stuck in maintenance mode they would be forced to patch an old release of the SDK or figure out a path forward through breaking changes?

We currently do not support LTS versions, so whatever issues occur in older versions are not considered. I don't see it viable for the Parse Flutter SDK in its current circumstances to introduce a LTS policy.

Great comment @chadpav, happy to revive this discussion.

**Comment by mtrezza** [comment]
@mbfakourii I've re-opened the issue and pinned it. Reason being that I'd like to briefly review the policy.

We keep getting issue reports regarding dependency upgrades, and we sometimes have to reject them due to the support policy. For example:

- https://github.com/parse-community/Parse-SDK-Flutter/issues/1020

We applied the support policy for a while now. Is it working and sensible as it is; should we improve anything?

**Comment by mbfakourii** [comment]
> Is the policy working and sensible as it is; should we improve anything?

I think considering the many issues, it is better to change the time from 1 year to 6 months.

Another point is that I did not see support policy in many packages in Dart and Flutter

Is support policy really needed for Dart and Flutter packages?

**Comment by mtrezza** [comment]
A support policy is simply making sure we have a consistent approach and don't need to initiate a discussion every time we need to make a choice. We can define the support policy as we see fit. If the philosophy of Dart and Flutter is that we always strive to support only the latest version of Dart and Flutter and its dependencies, we could define that as well (although that's not what I have found in my [analysis](https://github.com/parse-community/Parse-SDK-Flutter/issues/968#issuecomment-1741761786)). We just can't have a discussion then to suddenly keep supporting an older version. Instead we'd follow that policy.

**Comment by 2shrestha22** [comment]
I want to add my struggle with current policy. Previously it was with http package. Major package was already updated to latest http package but Parse SDK wasn't which was causing dependency issues. You may be asking why I need to upgrade. It's because I like to keep my app up-to-date and I have maintenance at the end of the month. I do upgrade, test and deploy each month so I don't have to deal with huge amount of changes Flutter ecosystem introduces later on.

Another issue I recently got when compiling my app for iOS 18 when using Firebase. There is an issue with iOS 18 and colder Firebase plugin version. It just won't compile. Fix is to update the firebase plugin to latest version. But release cycle don't let me update it because of dependency of Parse SDK with lower version of dependencies.

There will be huge changes in 6 months of time span. Policies are made to make things in order but if it's breaking the system we should change the policy. Instead of sticking to policy we should be prioritizing developer issues.

**Comment by mtrezza** [comment]
What is your policy suggestion in context of the arguments made previously in this thread?

**Comment by 2shrestha22** [comment]
> What is your policy suggestion in context of the arguments made previously in this thread?
I would say decrease the update time from 6 months to 3 where we do upgrade regularly every 3 months. Then we also take new issues into consideration. If someone reports a issue about dependency then we fix it immediately instead of waiting another 3 months.

**Comment by mtrezza** [comment]
> If someone reports a issue about dependency then we fix it immediately instead of waiting another 3 months.

That sounds like a contradiction. Why wait 3 months, if we wait 0 when someone requests a dependency upgrade?

**Comment by 2shrestha22** [comment]
No it's not a contradiction.
1. Not everyone complain about dependency unless it's unsolvable or causing severe issue.
2. After getting dependency upgrade issue we still can analyze the necessity.
3. Why 3 months? If no one complains about dependency issue that doesn't mean we should not upgrade it regularly.

**Comment by mtrezza** [comment]
That sounds too arbitrary. A complaint is not a technical basis for making a decision. And your suggestion is not addressing the arguments made previously.

**Comment by 2shrestha22** [comment]
> That sounds too arbitrary, why 3 months, why not 2 or 4? And complaint is not a technical basis for making a decision. Your suggestion is not addressing the arguments made previously, which give a reason for why the policy is currently as it is.

I think you are misunderstanding flutter SDK version and package dependency version. The comment in https://github.com/parse-community/Parse-SDK-Flutter/issues/968#issuecomment-1741761786 is about SDK version. I am not complaining about it. It is the package dependency we need to resolve.

**Comment by mtrezza** [comment]
> I think you are misunderstanding package dependency version with flutter SDK version. 

As I understand it, these two are related to each other. The reason why we cannot upgrade some dependencies is because of the dart / flutter version the SDK supports. If a dependency can be upgraded without requiring to modify the dart / flutter version, then we can always do that. In fact, such dependencies should be upgraded as soon as possible for bug fixes and security.

> We should pick whatever considering both maintainer and Parse SDK user.

Whatever number we pick, it should have a factual basis on data. Otherwise 3 months is as good as 6 months.

**Comment by 2shrestha22** [comment]
You can not relate Dart/Flutter SDK with package dependency since every package depends on Dart SDK. Package maintainers do not need to change dart SDK constraints frequently since the constraint we get when creating a project is already enough. If I create a dart package now I will get SDK constraints `3.4.3 <4.0.0` and the package is compatible with all dart version from 3.4.3 up to dart 4. However maintainer do update minimum dart version to make package compatible with latest changes in Dart or Flutter SDK. Before that they make sure new feature is stable and can be used in their package. And 1-2 months is more than enough for stability but we still waiting for 6 months.

Updating `http`, `device_info_plus` and `web_socket_channels` do not require any SDK constraints updates and does not break anything. I already have my app in production with latest packages. `http` package upgrade took months before it was merged. Developer are forced into trouble just for sake of policy even though it can be easily solved with regular updates.

**Comment by pastordee** [comment]
I think as long as there's no breaking changes, we should be able to update the SDK, I think someone mentioned earlier, most update as long as it does not have any new future is for bugs and security update so as a developer it is good to keep up with these updates

**Comment by mtrezza** [comment]
> If I create a dart package now I will get SDK constraints >=3.4.3 <4.0.0 and the package is compatible with all dart version from 3.4.3 up to dart 4. 

How is that possible if dart [3.5.0](https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#350---2024-08-06) already contains a breaking change? In my understanding, the dart and flutter SDK doesn't follow semver and breaking changes are introduced at a feature version level.

**Comment by 2shrestha22** [comment]
1. Developer requires dependency update when ParseSDK is already behind other packages.
2. When we upgrade the dependency it will not create an issue but solves the issue.

All of this points to dependency issue. The only question is how we are trying to fix the dependency issue. Holding back upgrades is not helping at all.

**Comment by 2shrestha22** [comment]
At least we can try making ParseSDK compatible with other major packages.

**Comment by mbfakourii** [comment]
> [@mbfakourii](https://github.com/mbfakourii) What do you suggest as a reasonable way out of this?

We tested for 1 year and saw the result
I suggest setting it to 6 months
What do you think ?

**Comment by mtrezza** [comment]
Sounds good, let's try it with 6 months then and review in 2026. I'll keep the issue open for now. Would you want to open a PR to make the change to our policy and I remove the versions that we don't need to support anymore?

**Comment by mbfakourii** [comment]
> Sounds good, let's try it with 6 months then and review in 2026. If you want we can also try out something more radical and always only support the latest version as soon as it's published, if that makes sense? I'll keep the issue open for now. Would you want to open a PR to make the change to our policy in the README? Looking at the [table](https://github.com/parse-community/Parse-SDK-Flutter/tree/master/packages/dart#compatibility), I think there are also versions that we don't need to support anymore?

Yes, I will set it to 6 months

**Comment by mtrezza** [comment]
@mbfakourii Great, I've already reviewed it.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [9.0.0](https://github.com/parse-community/Parse-SDK-Flutter/releases/tag/dart-9.0.0)
